//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostina.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guestc
    {
        public int IdGuestc { get; set; }
        public string NumberPassport { get; set; }
        public string NumberSeria { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Fetherland { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Adress { get; set; }
        public string Goal { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Zacebece Zacebece { get; set; }
    }
}
