//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostina.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GosEntities : DbContext
    {
        public GosEntities()
            : base("name=GosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Gostnomer> Gostnomer { get; set; }
        public DbSet<Guestc> Guestc { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<Zacebece> Zacebece { get; set; }
    }
}
