//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostina.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int IdSer { get; set; }
        public string Sefes { get; set; }
        public string Cost { get; set; }
        public string TimeServices { get; set; }
        public string Numberofvisits { get; set; }
        public string Img { get; set; }
    
        public virtual Zacebece Zacebece { get; set; }
    }
}
