//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gostina.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zacebece
    {
        public int Id { get; set; }
        public string NumberPassport { get; set; }
        public string Numbernomer { get; set; }
        public Nullable<System.DateTime> Zacelenie { get; set; }
        public Nullable<System.DateTime> Becelenie { get; set; }
        public string IdGost { get; set; }
        public string IdGuestc { get; set; }
    
        public virtual Gostnomer Gostnomer { get; set; }
        public virtual Guestc Guestc { get; set; }
        public virtual Services Services { get; set; }
    }
}
